# constantes da janela
DISPLAY_SIZE_X = 1024	
DISPLAY_SIZE_Y = 768

BUG_TIME = 8
PLACAR_JOGO = 35
NOME_MELHOR = "Carlos"

GAME_TIME = 25
BRAIN_RESPAWN_BORDER = 50

ZOMBIE_SPEED = 6
ZOMBIE_SLOWER_SPEED = 1
